version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: 095961074447
    AWS_DEFAULT_REGION: ap-southeast-1
    IMAGE_REPO_NAME_FRONTEND: dentist-appointment-client
    IMAGE_REPO_NAME_BACKEND: dentist-appointment-server
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      # Build Frontend Docker Image
      - cd client
      - docker build -t $IMAGE_REPO_NAME_FRONTEND:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME_FRONTEND:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_FRONTEND:$IMAGE_TAG
      - cd ..
      # Build Backend Docker Image
      - cd frontend
      - docker build -t $IMAGE_REPO_NAME_BACKEND:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME_BACKEND:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_BACKEND:$IMAGE_TAG
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`
      # Push Frontend Image
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_FRONTEND:$IMAGE_TAG
      # Push Backend Image
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_BACKEND:$IMAGE_TAG
